### ISSUE TITLE
BABEL_PARSER_SYNTAX_ERROR NumberIdentifier SyntaxError: Identifier directly after number. (121:3) at instantiate (node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:17646:36) at constructor)

### ISSUE THREAD

**Issue by 0xdevalias** [pionxzh/wakaru#52]
Attempting to unpack/unminify some webpacked code ([Ref](https://github.com/0xdevalias/chatgpt-source-watch/blob/main/unpacked/_next/static/chunks/pages/_app.js)):

```js
⇒ cd ./unpacked/_next/static/chunks

⇒ npx @wakaru/unpacker pages/_app.js -o ./pages/_app-unpacked/
Generated 213 modules from pages/_app.js to pages/_app-unpacked (24,049ms)

⇒ npx @wakaru/unminify ./pages/_app-unpacked/* -o ./pages/_app-unminified
# ..snip..
```

I got the following error while attempting to unminify:

```shell
# ..snip..

• Transforming pages/_app-unminified/pages/_app-unpacked/module-96733.js (900.5ms)
SyntaxError: Identifier directly after number. (121:3)
    at instantiate (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:17646:36)
    at constructor (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:17942:16)
    at FlowParserMixin.raise (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:20820:23)
    at FlowParserMixin.readNumber (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:20677:22)
    at FlowParserMixin.getTokenFromCode (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:20431:18)
    at FlowParserMixin.getTokenFromCode (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:24601:15)
    at FlowParserMixin.getTokenFromCode (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:22998:17)
    at FlowParserMixin.nextToken (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:19935:14)
    at FlowParserMixin.next (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:19845:14)
    at FlowParserMixin.parseObjectLike (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:29309:14) {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'NumberIdentifier',
  loc: Position { line: 121, column: 3, index: 1649 },
  pos: [Getter/Setter]
}
  119 | };
  120 | var tE = {
  121 |   2D: 0,
          ^
  122 |   WebGL: 1,
  123 |   WebGL2: 2,
• Transforming pages/_app-unminified/pages/_app-unpacked/module-96837.js (27,929.5ms)
# ..snip..
```

**Comment by pionxzh** [comment]
Fixed. This is because enum transformation generates invalid identifiers.
```js
var RenderMode = {
  "2D": 1,
  ^ 2D is not a valid identifier
  WebGL: 2,
  WebGL2: 3,
}
```
