### ISSUE TITLE
BABEL_PARSER_SYNTAX_ERROR VarRedeclaration SyntaxError: Identifier 'tag' has already been declared

### ISSUE THREAD

**Issue by 0xdevalias** [pionxzh/wakaru#54]
Attempting to unpack/unminify some webpacked code ([Ref](https://github.com/0xdevalias/chatgpt-source-watch/blob/main/unpacked/_next/static/chunks/pages/framework.js)):

```js
⇒ cd ./unpacked/_next/static/chunks

⇒ npx @wakaru/unpacker framework.js -o ./framework-unpacked/
Generated 9 modules from framework.js to framework-unpacked (3,800.3ms)

⇒ npx @wakaru/unminify ./framework-unpacked/* -o ./framework-unminified
```

I got the following error while attempting to unminify:

```
# ..snip..
• Transforming framework-unminified/framework-unpacked/module-2226.js (171.3ms)
SyntaxError: Identifier 'tag' has already been declared. (2491:14)
    at instantiate (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:17646:36)
    at constructor (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:17942:16)
    at FlowParserMixin.raise (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:20820:23)
    at FlowScopeHandler.checkRedeclarationInScope (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:19076:23)
    at FlowScopeHandler.declareName (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:19058:18)
    at FlowScopeHandler.declareName (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:19144:15)
    at FlowParserMixin.declareNameFromIdentifier (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:25112:20)
    at FlowParserMixin.checkIdentifier (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:25108:16)
    at FlowParserMixin.checkLVal (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:25046:16)
    at FlowParserMixin.checkLVal (/Users/devalias/dev/0xdevalias/REDACTED/node_modules/@wakaru/unminify/dist/chunk-AY7YAENM.cjs:25078:18) {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'VarRedeclaration',
  loc: Position { line: 2491, column: 14, index: 54940 },
  pos: [Getter/Setter]
}
 2489 |           for (tag = r.return; tag !== null; ) {
 2490 |             var {
 2491 |               tag
                     ^
 2492 |             } = tag;
 2493 |             if ((tag === 3 || tag === 4) &&
• Transforming framework-unminified/framework-unpacked/module-2920.js (59,842.4ms)
# ..snip..
```

---

Looking at `module-2920.js`, it's:

```
/**
 * @license React
 * react-dom.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
```

```
version: "18.2.0",
rendererPackageName: "react-dom",
```

```
reconcilerVersion: "18.2.0-next-9e3b772b8-20220608",
```

```
(exports.version = "18.2.0-next-9e3b772b8-20220608");
```

**Comment by pionxzh** [comment]
Reopen. I just remembered that I needed to add a test for it.
